import type { Metadata } from "next";

import { Poppins } from "@next/font/google";
// import "./globals.css";

import "@/public/style/style.css";
import "@/public/style/responsive.css";
import "@/public/style/owl.css";
import "@/public/style/jquery.fancybox.min.css";
import "@/public/style/jquery-ui.min.css";
import "@/public/style/fontawesome-all.css";
import "@/public/style/flaticon.css";
import "@/public/style/bootstrap.css";
import "@/public/style/animate.css";
import Header from "@/component/Header";
import Footer from "@/component/Footer";
import { ToastContainer } from "react-toastify";
import ScrollTop from "@/component/ScrollTop";

// import Home from "./page";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap", // Ensures text is visible while font loads
});

export const metadata: Metadata = {
  title: "amfics.io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha512-..."
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className={poppins.className}>
        <ToastContainer
          position="bottom-right"
          autoClose={4000}
          style={{ zIndex: "9999" }}
        />
        <Header />
        {children}
        <Footer />
        <ScrollTop />
      </body>
    </html>
  );
}
